fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev:  24.3.0
    hooks:
      - id:               black
        language_version: python3.7
  - repo: local
    hooks:
      - id:             pytest-check
        name:           pytest-check
        entry:          pytest
        language:       system
        pass_filenames: false
        always_run:     true